INSERT INTO post (id, source, position_title, company_name, url_ref, posted_date, salary_high, is_open, closing_date, applicants, description, industry_classification, mcf_ref, src_method, run_id) VALUES ('MyCareerFutures-771e413d7bc340c16dfeac6ba88503ff', 'MyCareerFutures', 'gen ai engineer', 'APAR TECHNOLOGIES PTE. LTD.', 'https://www.mycareersfuture.gov.sg/job/information-technology/gen-ai-engineer-apar-technologies-771e413d7bc340c16dfeac6ba88503ff', '2026-07-26', 12000, 0, '2026-08-23', 17, NULL, NULL, NULL, 'scraped', 1);
INSERT INTO post (id, source, position_title, company_name, url_ref, posted_date, salary_high, is_open, closing_date, applicants, description, industry_classification, mcf_ref, src_method, run_id) VALUES ('MyCareerFutures-ba8ace4ad4d006a1f179ace0860a9657', 'MyCareerFutures', 'solution architect data and gen ai', 'APAR TECHNOLOGIES PTE. LTD.', 'https://www.mycareersfuture.gov.sg/job/information-technology/solution-architect-apar-technologies-ba8ace4ad4d006a1f179ace0860a9657', '2026-07-24', 14000, 0, '2026-08-21', 12, NULL, NULL, NULL, 'scraped', 1);
INSERT INTO post (id, source, position_title, company_name, url_ref, posted_date, salary_high, is_open, closing_date, applicants, description, industry_classification, mcf_ref, src_method, run_id) VALUES ('MyCareerFutures-706df6d5e0363c9405c7b687472ba79e', 'MyCareerFutures', 'gen ai engineer rag', 'PERSOL SINGAPORE PTE. LTD.', 'https://www.mycareersfuture.gov.sg/job/information-technology/gen-ai-engineer-rag-persol-singapore-706df6d5e0363c9405c7b687472ba79e', '2026-07-20', 10500, 0, '2026-08-17', 32, NULL, NULL, NULL, 'scraped', 1);
-- synthetic below-threshold or lifecycle fixture
INSERT INTO post (id, source, position_title, company_name, url_ref, posted_date, salary_high, is_open, closing_date, applicants, description, industry_classification, mcf_ref, src_method, run_id) VALUES ('synthetic-1', 'Synthetic', 'Seed PROSPECT role', 'Synthetic Company', 'https://www.mycareersfuture.gov.sg/job/synthetic-1', '2026-09-14', 10000, 1, NULL, 0, NULL, NULL, NULL, 'manual', NULL);
-- synthetic below-threshold or lifecycle fixture
INSERT INTO post (id, source, position_title, company_name, url_ref, posted_date, salary_high, is_open, closing_date, applicants, description, industry_classification, mcf_ref, src_method, run_id) VALUES ('synthetic-2', 'Synthetic', 'Seed TOAPPLY role', 'Synthetic Company', 'https://www.mycareersfuture.gov.sg/job/synthetic-2', '2026-09-13', 10000, 1, NULL, 0, NULL, NULL, NULL, 'manual', NULL);
-- synthetic below-threshold or lifecycle fixture
INSERT INTO post (id, source, position_title, company_name, url_ref, posted_date, salary_high, is_open, closing_date, applicants, description, industry_classification, mcf_ref, src_method, run_id) VALUES ('synthetic-3', 'Synthetic', 'Seed APPLIED role', 'Synthetic Company', 'https://www.mycareersfuture.gov.sg/job/synthetic-3', '2026-09-12', 10000, 1, NULL, 0, NULL, NULL, NULL, 'manual', NULL);
-- synthetic below-threshold or lifecycle fixture
INSERT INTO post (id, source, position_title, company_name, url_ref, posted_date, salary_high, is_open, closing_date, applicants, description, industry_classification, mcf_ref, src_method, run_id) VALUES ('synthetic-4', 'Synthetic', 'Seed CALLBACK role', 'Synthetic Company', 'https://www.mycareersfuture.gov.sg/job/synthetic-4', '2026-09-11', 10000, 1, NULL, 0, NULL, NULL, NULL, 'manual', NULL);
-- synthetic below-threshold or lifecycle fixture
INSERT INTO post (id, source, position_title, company_name, url_ref, posted_date, salary_high, is_open, closing_date, applicants, description, industry_classification, mcf_ref, src_method, run_id) VALUES ('synthetic-5', 'Synthetic', 'Seed INTERVIEW role', 'Synthetic Company', 'https://www.mycareersfuture.gov.sg/job/synthetic-5', '2026-09-10', 10000, 1, NULL, 0, NULL, NULL, NULL, 'manual', NULL);
-- synthetic below-threshold or lifecycle fixture
INSERT INTO post (id, source, position_title, company_name, url_ref, posted_date, salary_high, is_open, closing_date, applicants, description, industry_classification, mcf_ref, src_method, run_id) VALUES ('synthetic-6', 'Synthetic', 'Seed OFFER role', 'Synthetic Company', 'https://www.mycareersfuture.gov.sg/job/synthetic-6', '2026-09-09', 10000, 1, NULL, 0, NULL, NULL, NULL, 'manual', NULL);
-- synthetic below-threshold or lifecycle fixture
INSERT INTO post (id, source, position_title, company_name, url_ref, posted_date, salary_high, is_open, closing_date, applicants, description, industry_classification, mcf_ref, src_method, run_id) VALUES ('synthetic-closed', 'Synthetic', 'Seed closed role', 'Synthetic Company', 'https://www.mycareersfuture.gov.sg/job/synthetic-closed', '2026-09-05', 10000, 0, '2026-09-14', 0, NULL, NULL, NULL, 'manual', NULL);
-- synthetic below-threshold or lifecycle fixture
INSERT INTO post (id, source, position_title, company_name, url_ref, posted_date, salary_high, is_open, closing_date, applicants, description, industry_classification, mcf_ref, src_method, run_id) VALUES ('synthetic-close-11', 'Synthetic', 'Seed close reason role', 'Synthetic Company', 'https://www.mycareersfuture.gov.sg/job/synthetic-close-11', '2026-09-04', 10000, 1, NULL, 0, NULL, NULL, NULL, 'manual', NULL);
-- synthetic below-threshold or lifecycle fixture
INSERT INTO post (id, source, position_title, company_name, url_ref, posted_date, salary_high, is_open, closing_date, applicants, description, industry_classification, mcf_ref, src_method, run_id) VALUES ('synthetic-close-12', 'Synthetic', 'Seed close reason role', 'Synthetic Company', 'https://www.mycareersfuture.gov.sg/job/synthetic-close-12', '2026-09-03', 10000, 1, NULL, 0, NULL, NULL, NULL, 'manual', NULL);
-- synthetic below-threshold or lifecycle fixture
INSERT INTO post (id, source, position_title, company_name, url_ref, posted_date, salary_high, is_open, closing_date, applicants, description, industry_classification, mcf_ref, src_method, run_id) VALUES ('synthetic-close-13', 'Synthetic', 'Seed close reason role', 'Synthetic Company', 'https://www.mycareersfuture.gov.sg/job/synthetic-close-13', '2026-09-02', 10000, 1, NULL, 0, NULL, NULL, NULL, 'manual', NULL);
